
#Search Journals
# POST http://localhost:5000/api/journals?page=4&limit=10

# content-type: application/json


##Get all journals
# GET http://localhost:5000/api/journals/all?page=1&limit=5

##Get all pending journals
# GET http://localhost:5000/api/journals/pending?page=1&limit=5



##get a journal by Id
GET  http://localhost:5000/api/journals/9

##Delete A Particular Journal 
# DELETE http://localhost:5000/api/journals/delete/7304


# Register a user VW4p9Q0Bn9
POST  http://localhost:5000/api/users/signup
Content-Type: application/json
{
    "firstName" : "admin",
    "lastName" : "isi",
    "email" : "admin@intellectscientificinformation.com",
    "jobTitle" : "admin",
    "password": "VW4p9Q0Bn9"

}



# GET http://intellectscientificinformation.com:5000/api/coverage-index

POST http://localhost:5000/api/journals/coverage-indexes?page=1&limit=15
Content-Type: application/json 

{   
    "coverageIndex" : "Science coverage Index"
} 