
##Search Journals
# POST http://localhost:5000/api/journals?page=1&limit=2

# content-type: application/json

# {
#     "search": "first"
# }


##Get all journals
# GET http://localhost:5000/api/journals/all?page=1&limit=5

##Get all pending journals
# GET http://localhost:5000/api/journals/pending?page=1&limit=5



##get a journal by Id
# GET  http://localhost:5000/api/journals/9

# Register a user VW4p9Q0Bn9
POST  http://localhost:5000/api/users/signup
Content-Type: application/json

{
    "firstName" : "admin",
    "lastName" : "isi",
    "email" : "admin@intellectscientificinformation.com",
    "jobTitle" : "admin",
    "password": "VW4p9Q0Bn9"

}